packaging_format = 2

id = "kavita"
name = "Kavita"
description.en = "Media server for your comics, manga and books"
description.fr = "Serveur multimédia pour vos bandes dessinées, mangas et livres"

version = "0.7.10.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "www.kavitareader.com"
demo = "https://demo.kavitareader.com/"
admindoc = "https://wiki.kavitareader.com/en"
code = "https://github.com/Kareadita/Kavita"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "300M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/kavita"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]
        [resources.sources.main]
        in_subdir = true
        amd64.url = "https://github.com/Kareadita/Kavita/releases/download/v0.7.10.1/kavita-linux-x64.tar.gz"
        amd64.sha256 = "fedeff6225943e4fee5ddc62469be5f4b8729b6eb6277c183ace2962b8adff34"
        arm64.url = "https://github.com/Kareadita/Kavita/releases/download/v0.7.10.1/kavita-linux-arm64.tar.gz"
        arm64.sha256 = "b5921aa510e5802f114a73e5463a57ea4cc4314ae6bcf3bc1e9cc26342f3f05b"
        armhf.url = "https://github.com/Kareadita/Kavita/releases/download/v0.7.10.1/kavita-linux-arm.tar.gz"
        armhf.sha256 = "8cd6693ab87f1e4f4226476f79a6a0223c56eb5f829fef4d03053d6699fe66a5"

        # https://yunohost.org/fr/packaging_apps_resources#regarding-autoupdate
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "kavita-linux-x64.tar.gz"
        autoupdate.asset.arm64 = "kavita-linux-arm64.tar.gz"
        autoupdate.asset.armhf = "kavita-linux-arm.tar.gz"

    [resources.ports]
    main.default = 5000

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    api.url = "/api"
    api.show_tile = false
    api.protected= true
    api.allowed = ["visitors", "all_users"]
    api.auth_header = false

    hubs.url = "/hubs"
    hubs.show_tile = false
    hubs.protected= true
    hubs.auth_header = false
    hubs.allowed = ["visitors", "all_users"]

    [resources.apt]
    packages = "sqlite3"
