packaging_format = 2

id = "kavita"
name = "Kavita"
description.en = "Media server for your comics, manga and books"
description.fr = "Serveur multimédia pour vos bandes dessinées, mangas et livres"

version = "0.7.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "www.kavitareader.com"
demo = "https://demo.kavitareader.com/"
admindoc = "https://wiki.kavitareader.com/en"
code = "https://github.com/Kareadita/Kavita"

[integration]
yunohost = ">= 11.1.19"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "300M"
ram.runtime = "50M"

[install]
    [install.domain]

    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/Kareadita/Kavita/releases/download/v0.7.1/kavita-linux-x64.tar.gz"
    amd64.sha256 = "B67B91E97F490D0629AAD00E2B2E78752C57A2E7BDD00D3E1B1461EFEF5F22BA"
    arm64.url = "https://github.com/Kareadita/Kavita/releases/download/v0.7.1/kavita-linux-arm64.tar.gz"
    arm64.sha256 = "DEA4160C72B024BEB47565526DBD71512E8EEB65360D22E76A7E695C0A4C55B7"
    armhf.url = "https://github.com/Kareadita/Kavita/releases/download/v0.7.1/kavita-linux-arm.tar.gz"
    armhf.sha256 = "AD5CEC73D6B5B48386EAC5291CD9C4B40F0AF4FBB712E730518D3605E80F1D52"

    [resources.ports]
    main.default = 5000
    
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    api.url = "/api"
    api.show_tile = false
    api.protected= true
    api.allowed = ["visitors", "all_users"]

    hubs.url = "/hubs/*"
    hubs.show_tile = false
    hubs.protected= true
    hubs.auth_header = false
    hubs.allowed = ["visitors", "all_users"]

    [resources.apt]
    packages = "sqlite3"
