#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "kavita"
name = "Kavita"
description.en = "Media server for your comics, manga and books"
description.fr = "Serveur multimédia pour vos bandes dessinées, mangas et livres"

version = "0.8.3.2~ynh1"

maintainers = [ "eric_G" ]

[upstream]
license = "MIT"
website = "https://www.kavitareader.com/"
demo = "https://demo.kavitareader.com/"
admindoc = "https://wiki.kavitareader.com/en"
code = "https://github.com/Kareadita/Kavita"

[integration]
yunohost = ">= 11.2"
architectures = [ "amd64", "arm64", "armhf" ]
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "300M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/kavita"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]
        [resources.sources.main]
        in_subdir = true
        amd64.url = "https://github.com/Kareadita/Kavita/releases/download/v0.8.3.2/kavita-linux-x64.tar.gz"
        amd64.sha256 = "6d4a91cfcecd80d710fa16a750206418ea636c44fd158327509a3daf48149e08"
        arm64.url = "https://github.com/Kareadita/Kavita/releases/download/v0.8.3.2/kavita-linux-arm64.tar.gz"
        arm64.sha256 = "dbf45d440ef6589b53432752e8b3f98ed45693e82082646de60baffcbdaf65f1"
        armhf.url = "https://github.com/Kareadita/Kavita/releases/download/v0.8.3.2/kavita-linux-arm.tar.gz"
        armhf.sha256 = "8f3756936138c78c098f8e79c7be8f38c5c1d3ecf55235bfd4978c33ccf2f2c3"

        # https://yunohost.org/fr/packaging_apps_resources#regarding-autoupdate
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "kavita-linux-x64.tar.gz"
        autoupdate.asset.arm64 = "kavita-linux-arm64.tar.gz"
        autoupdate.asset.armhf = "kavita-linux-arm.tar.gz"

[resources.ports]
main.default = 5000

[resources.system_user]

[resources.install_dir]

[resources.permissions]
main.url = "/"

api.url = "/api"
api.show_tile = false
api.protected = true
api.allowed = [ "visitors", "all_users" ]
api.auth_header = false

hubs.url = "/hubs"
hubs.show_tile = false
hubs.protected = true
hubs.auth_header = false
hubs.allowed = [ "visitors", "all_users" ]

[resources.apt]
packages = "sqlite3"
