packaging_format = 2

id = "kavita"
name = "Kavita"
description.en = "Media server for your comics, manga and books"
description.fr = "Serveur multimédia pour vos bandes dessinées, mangas et livres"

version = "0.7.11.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "www.kavitareader.com"
demo = "https://demo.kavitareader.com/"
admindoc = "https://wiki.kavitareader.com/en"
code = "https://github.com/Kareadita/Kavita"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "300M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/kavita"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]
        [resources.sources.main]
        in_subdir = true
        amd64.url = "https://github.com/Kareadita/Kavita/releases/download/v0.7.11.1/kavita-linux-x64.tar.gz"
        amd64.sha256 = "43d817ab75d4de3c791eea04e20e2f3f6c04a9cac9ca55b69b49e3377f9b3655"
        arm64.url = "https://github.com/Kareadita/Kavita/releases/download/v0.7.11.1/kavita-linux-arm64.tar.gz"
        arm64.sha256 = "9453104ecbbdfd64b2ebc8ca8616e5c4a1c199ffa56d1a03030d2e40acdd58fe"
        armhf.url = "https://github.com/Kareadita/Kavita/releases/download/v0.7.11.1/kavita-linux-arm.tar.gz"
        armhf.sha256 = "9c970943e1ce751f89ce18f4fccf3efa8b77e8875f222b815a257837713feb3f"

        # https://yunohost.org/fr/packaging_apps_resources#regarding-autoupdate
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "kavita-linux-x64.tar.gz"
        autoupdate.asset.arm64 = "kavita-linux-arm64.tar.gz"
        autoupdate.asset.armhf = "kavita-linux-arm.tar.gz"

    [resources.ports]
    main.default = 5000

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    api.url = "/api"
    api.show_tile = false
    api.protected= true
    api.allowed = ["visitors", "all_users"]
    api.auth_header = false

    hubs.url = "/hubs"
    hubs.show_tile = false
    hubs.protected= true
    hubs.auth_header = false
    hubs.allowed = ["visitors", "all_users"]

    [resources.apt]
    packages = "sqlite3"
