#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "kavita"
name = "Kavita"
description.en = "Media server for your comics, manga and books"
description.fr = "Serveur multimédia pour vos bandes dessinées, mangas et livres"

version = "0.8.0~ynh1"

maintainers = [ "eric_G" ]

[upstream]
license = "MIT"
website = "https://www.kavitareader.com/"
demo = "https://demo.kavitareader.com/"
admindoc = "https://wiki.kavitareader.com/en"
code = "https://github.com/Kareadita/Kavita"

[integration]
yunohost = ">= 11.2"
architectures = [ "amd64", "arm64", "armhf" ]
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "300M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/kavita"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]
        [resources.sources.main]
        in_subdir = true
        amd64.url = "https://github.com/Kareadita/Kavita/releases/download/v0.8.0/kavita-linux-x64.tar.gz"
        amd64.sha256 = "84702cce150403fb4830e29e13097b395887b58cc487bf0701388b306a22c647"
        arm64.url = "https://github.com/Kareadita/Kavita/releases/download/v0.8.0/kavita-linux-arm64.tar.gz"
        arm64.sha256 = "6c4d87af649dc79b8004b687f5ceb78a4c09efb7f9ef2b80a4e243cb55b0b9bc"
        armhf.url = "https://github.com/Kareadita/Kavita/releases/download/v0.8.0/kavita-linux-arm.tar.gz"
        armhf.sha256 = "c7d8ac8c59bb1551a434a545db02771bc5eda301344e03f801bea78e9e22b43e"

        # https://yunohost.org/fr/packaging_apps_resources#regarding-autoupdate
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "kavita-linux-x64.tar.gz"
        autoupdate.asset.arm64 = "kavita-linux-arm64.tar.gz"
        autoupdate.asset.armhf = "kavita-linux-arm.tar.gz"

[resources.ports]
main.default = 5000

[resources.system_user]

[resources.install_dir]

[resources.permissions]
main.url = "/"

api.url = "/api"
api.show_tile = false
api.protected = true
api.allowed = [ "visitors", "all_users" ]
api.auth_header = false

hubs.url = "/hubs"
hubs.show_tile = false
hubs.protected = true
hubs.auth_header = false
hubs.allowed = [ "visitors", "all_users" ]

[resources.apt]
packages = "sqlite3"
