packaging_format = 2

id = "kavita"
name = "Kavita"
description.en = "Media server for your comics, manga and books"
description.fr = "Serveur multimédia pour vos bandes dessinées, mangas et livres"

version = "0.7.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "www.kavitareader.com"
demo = "https://demo.kavitareader.com/"
admindoc = "https://wiki.kavitareader.com/en"
code = "https://github.com/Kareadita/Kavita"

[integration]
yunohost = ">= 11.1.9"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]

    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.ports]
    
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    api.url = "/api"
    api.show_tile = false
    api.protected= true
    api.allowed = ["visitors", "all_users"]

    hubs.url = "/hubs/*"
    hubs.show_tile = false
    hubs.protected= true
    hubs.auth_header = false
    hubs.allowed = ["visitors", "all_users"]

    [resources.apt]
    packages = "sqlite3"
