#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "kavita"
name = "Kavita"
description.en = "Media server for your comics, manga and books"
description.fr = "Serveur multimédia pour vos bandes dessinées, mangas et livres"

version = "0.8.7~ynh1"

maintainers = [ ]

[upstream]
license = "MIT"
website = "https://www.kavitareader.com/"
demo = "https://demo.kavitareader.com/"
admindoc = "https://wiki.kavitareader.com/en"
code = "https://github.com/Kareadita/Kavita"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = [ "amd64", "arm64", "armhf" ]
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "300M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/kavita"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = true
    amd64.url = "https://github.com/Kareadita/Kavita/releases/download/v0.8.7/kavita-linux-x64.tar.gz"
    amd64.sha256 = "88ea7862ae732a80e562139d3fa5e404f52b3762af8ec5ae2e83266e251f63e4"
    arm64.url = "https://github.com/Kareadita/Kavita/releases/download/v0.8.7/kavita-linux-arm64.tar.gz"
    arm64.sha256 = "e54108d9a39258d1bed77e4abeff5419d04f146a15c2c0d862e8354eb5634276"
    armhf.url = "https://github.com/Kareadita/Kavita/releases/download/v0.8.7/kavita-linux-arm.tar.gz"
    armhf.sha256 = "dd2f556ccc17d9d241871f451964a19169871d6a58f1f3de2af8627c8b022ed8"

    # https://yunohost.org/fr/packaging_apps_resources#regarding-autoupdate
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "kavita-linux-x64.tar.gz"
    autoupdate.asset.arm64 = "kavita-linux-arm64.tar.gz"
    autoupdate.asset.armhf = "kavita-linux-arm.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    api.url = "/api"
    api.show_tile = false
    api.protected = true
    api.allowed = [ "visitors", "all_users" ]
    api.auth_header = false

    hubs.url = "/hubs"
    hubs.show_tile = false
    hubs.protected = true
    hubs.auth_header = false
    hubs.allowed = [ "visitors", "all_users" ]

    [resources.ports]
    main.default = 5000

    [resources.apt]
    packages = "sqlite3"
