#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "kavita"
name = "Kavita"
description.en = "Media server for your comics, manga and books"
description.fr = "Serveur multimédia pour vos bandes dessinées, mangas et livres"

version = "0.9.0.2~ynh1"

maintainers = [ ]

[upstream]
license = "MIT"
website = "https://www.kavitareader.com/"
demo = "https://demo.kavitareader.com/"
admindoc = "https://wiki.kavitareader.com/en"
code = "https://github.com/Kareadita/Kavita"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = [ "amd64", "arm64", "armhf" ]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "300M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/kavita"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = true
    amd64.url = "https://github.com/Kareadita/Kavita/releases/download/v0.9.0.2/kavita-linux-x64.tar.gz"
    amd64.sha256 = "7bec1747802a03daf3b5d42fabfa288c491b1d0dc5d47c4cce1dc32b6391b323"
    arm64.url = "https://github.com/Kareadita/Kavita/releases/download/v0.9.0.2/kavita-linux-arm64.tar.gz"
    arm64.sha256 = "8c80a35765d35b82018938084050f8057318bbbf840e0b3d80d2a72dc5ba136e"
    armhf.url = "https://github.com/Kareadita/Kavita/releases/download/v0.9.0.2/kavita-linux-arm.tar.gz"
    armhf.sha256 = "7aadcbcce2483a445d9c7f52659fbefa06afcca0ea3b4fa6dd19f32a2bb5cc25"

    # https://yunohost.org/fr/packaging_apps_resources#regarding-autoupdate
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "kavita-linux-x64.tar.gz"
    autoupdate.asset.arm64 = "kavita-linux-arm64.tar.gz"
    autoupdate.asset.armhf = "kavita-linux-arm.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    api.url = "/api"
    api.show_tile = false
    api.protected = true
    api.allowed = [ "visitors", "all_users" ]
    api.auth_header = false

    hubs.url = "/hubs"
    hubs.show_tile = false
    hubs.protected = true
    hubs.auth_header = false
    hubs.allowed = [ "visitors", "all_users" ]

    [resources.ports]
    main.default = 5000

    [resources.apt]
    packages = "sqlite3"
