#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action=stop --log_path=systemd

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
# CONFIGURE Kavita
#=================================================
ynh_backup_if_checksum_is_different "$install_dir/config/appsettings.json"

key=$(ynh_app_setting_get --key=key)
domain="$new_domain"
ynh_app_setting_set --key=domain --value="$domain"
url_path=${new_path#/}
if [ "$url_path" == "" ]; then url_path="/"; fi
ynh_app_setting_set --key=url_path --value="$url_path"

ynh_config_add --template="appsettings.json.example" --destination="$install_dir/config/appsettings.json"

#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 400 "$install_dir/config/appsettings.json"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown "$app":"$app" "$install_dir/config/appsettings.json"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action=start --log_path=systemd --wait_until="Now listening on:"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Change of URL completed for $app"
