#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

# compare if the system arch is different from the binary arch
# if so, download the correct binary
if [ "$(uname -m)" != "$(file "$install_dir"/Kavita | cut -d ',' -f 2 | tr -d ' ')" ]
then
	ynh_script_progression "Migrating binary architecture..."

	ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="config"
fi

chmod +x "$install_dir"/Kavita

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app".service --quiet

mkdir -p "/var/log/$app"
chmod 640 "/var/log/$app"

ynh_config_add_logrotate

yunohost service add "$app" --description="Cross platform reading server" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app" --action="start" --log_path="systemd" --wait_until="Now listening on:"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
