#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="config"

chmod +x "$install_dir"/Kavita

#=================================================
# MODIFY A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

key=$(ynh_app_setting_get --key=key)

if [ -z "$key" ] || [ "$key" == "super secret unguessable key that is longer because we require it" ]
then
	key=$(ynh_string_random --length=70)
	ynh_app_setting_set --key=key --value="$key"
fi

url_path=$(ynh_app_setting_get --key=url_path)

if [ -z "$url_path" ]; then
	url_path=${path#/}
	if [ "$url_path" == "" ]; then url_path="/"; fi
	ynh_app_setting_set --key=url_path --value="$url_path"
fi

ynh_config_add --template="appsettings.json.example" --destination="$install_dir/config/appsettings.json"

chmod 600 "$install_dir/config/appsettings.json"
chown "$app":"$app" "$install_dir/config/appsettings.json"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

mkdir -p "/var/log/$app"
chmod 640 "/var/log/$app"

ynh_config_add_logrotate

yunohost service add "$app" --description="Cross platform reading server" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="systemd" --wait_until="Now listening on:"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
